In [3]:
!pip install numpy

In [4]:

import numpy as np 

In [5]:
Array1 = np.array([2,5,89,6]) 

print(Array1)

[ 2  5 89  6]


In [6]:
Array2= np.array([1,2,3,4,5,6,7,8])

print(Array2.shape) 

(8,)


In [9]:
Matris = Array2.reshape(2,4) 
print(Matris)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:

print("shape: ",Matris.shape)

print("dimension: ",Matris.ndim) 

print("data type: ",Matris.dtype.name) 

print("size: ",Matris.size) 
                       
print("type",type(Matris))

shape:  (2, 4)
dimension:  2
data type:  int32
size:  8
type <class 'numpy.ndarray'>


In [12]:
Array3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(Array3.shape) 

(3, 4)


In [15]:

zeros= np.zeros((2,3))  
zeros[0,0]=4
print(zeros)

[[4. 0. 0.]
 [0. 0. 0.]]


In [16]:

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((6,7))

array([[1.24413698e-311, 1.24413709e-311, 1.35566986e+131,
        5.36793230e+242, 3.92880998e+160, 5.50409570e+257,
        2.59345414e+161],
       [5.56206154e+180, 8.17434450e+141, 1.09918035e+155,
        4.26209394e+180, 1.34452472e+161, 5.04620658e+180,
        3.57885821e+246],
       [6.01121703e+175, 4.73544978e+223, 8.90302838e+247,
        9.77146823e-153, 1.96097649e+243, 6.99405043e-009,
        2.93494529e+222],
       [1.03063392e-113, 1.72731111e+097, 6.99416121e-009,
        2.93494530e+222, 1.03063392e-113, 1.05894612e-153,
        7.61402229e-010],
       [8.98752578e-153, 4.83245960e+276, 8.03704345e-095,
        1.95575364e-109, 1.05190656e-153, 5.09600861e-307,
        1.24413727e-311],
       [1.24409642e-311, 1.05177053e-153, 7.04134408e-009,
        1.43178810e-065, 1.35717430e+131, 1.05176086e-153,
        4.03154109e+103]])

In [19]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [20]:

Array3= np.linspace(0,10,20)
print(Array3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [21]:

X= np.array([4,5,6])
Y= np.array([7,8,9]) 
print(X+Y) 
print(X-Y)
print(Y**2)

[11 13 15]
[-3 -3 -3]
[49 64 81]


In [23]:
x= np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [24]:
Liste = [1,5,6,2,11,7,9]

Liste_Array = np.array([5,6,7,8]) 
print(Liste_Array)
print(Liste)

[5 6 7 8]
[1, 5, 6, 2, 11, 7, 9]


In [25]:
Array = np.array(Liste)
print(Array)

[ 1  5  6  2 11  7  9]


In [26]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [29]:
b=a

c=a

b[0]=6
print(a,b,c)

[6 2 3] [6 2 3] [6 2 3]


In [30]:

d = a.copy()
print(d)

[6 2 3]


In [33]:
a= np.array([1,2,3,4,5,6,7,8,9]) 
print(a[5])
print(a[0:2])

6
[1 2]


In [34]:

reverse_array = a[::-5] 
print(reverse_array)

[9 4]


In [35]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
